set_property SRC_FILE_INFO {cfile:{D:/semester/7th sem/davinci/testing/IO/Processor.srcs/constrs_1/new/zybo.xdc} rfile:../../../../../Processor.srcs/constrs_1/new/zybo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name clk_pin -add [get_ports sysclk]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfb_in -source [get_pins dispDriver/MMCME2_BASE_INST/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_pin] [get_pins dispDriver/MMCME2_BASE_INST/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name MMCM_pix_clock -source [get_pins dispDriver/MMCME2_BASE_INST/CLKIN1] -edges {1 2 3} -edge_shift {0.000 16.000 32.000} -add -master_clock [get_clocks clk_pin] [get_pins dispDriver/MMCME2_BASE_INST/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name DCM_TMDS_CLKFX -source [get_pins dispDriver/MMCME2_BASE_INST/CLKIN1] -multiply_by 2 -add -master_clock [get_clocks clk_pin] [get_pins dispDriver/MMCME2_BASE_INST/CLKOUT2]
